version: '3.8'

services:
  ros2_dev:
    build: .
    container_name: hospibot
    privileged: true  # Gives the container full hardware access
    devices:
      - /dev/hci0 # bluetooth device
    volumes:
      - /dev:/dev  # Share all devices (useful if device changes dynamically)
    stdin_open: true
    tty: true
